services:
  controlled-vocabolary-interface:
    image: controlled-vocabolary-interface:prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3000"
    environment:
      # GraphDB Connection Configuration
      GRAPHDB_BASE_URL: "https://graphdb.voc.dev.epsilon-italia.it"
      GRAPHDB_USERNAME: ""
      GRAPHDB_PASSWORD: ""
      
      # Repository IDs per vocabulary
      CHRONOSTRATIGRAPHY_REPO_ID: "Chronostratigraphy_test_2_core"
      TECTONICUNITS_REPO_ID: "TectonicUnits_test_2_core"
      LITHOSTRATIGRAPHY_REPO_ID: "Lithostratigraphy_test_2_core"
      LITHOLOGY_REPO_ID: "Lithology_test_2_core"
      
      # Vocabulary Prefix Base URL (for SPARQL queries)
      VOCABULARY_PREFIX_URL: "https://lexic.swisstopo.demo.epsilon-italia.it"
      GOOGLE_ANALYTICS_ID:
      GITHUB_OWNER: swisstopo

      CHRONOSTRATIGRAPHY_REPO_SLUG: swissgeol-lexic-vocabulary-chronostratigrafie
      TECTONICUNITS_REPO_SLUG: swissgeol-lexic-vocabulary-tektonik
      LITHOSTRATIGRAPHY_REPO_SLUG: swissgeol-lexic-vocabulary-lithostratigrafie
      LITHOLOGY_REPO_SLUG: swissgeol-lexic-vocabulary-lithologie
